name: Build and Export IPA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: actions/setup-xcode@v1
        with:
          xcode-version: '15.0' # 원하는 Xcode 버전으로 조정

      - name: Build Xcode Project
        run: |
          xcodebuild -project web/web.xcodeproj \
            -scheme web \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/web.xcarchive \
            archive

      - name: Export IPA with Manual Signing
        run: |
          xcodebuild -exportArchive \
            -archivePath build/web.xcarchive \
            -exportPath build/web \
            -exportOptionsPlist exportOptions.plist \
            -allowProvisioningUpdates

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: web-ipa
          path: build/web/*.ipa